### ISSUE TITLE
Too large whitespace

### ISSUE THREAD

**Issue by pozitron57** [cdelker/schemdraw#1]
How can I control and trim the whitespace? matplotlib has `bbox_inches='tight'`, is there something similar that can be used with schemdraw? The following code gives too much of blank space to the left of the actual figure. I tried svg backend, different formats, but it is always the same.

``` python
import schemdraw
import schemdraw.elements as elm

with schemdraw.Drawing() as d:
    E = d.add(elm.BatteryCell().up().label('$\mathcal{E}$'))
    d += elm.Capacitor(polar=True).right().label('$C$').reverse()
    d += elm.Inductor2().down().label('$L$',loc='bot')
    d += elm.Switch(action='close').left().label('$K$')

d.save('file.svg')
```

**Comment by cdelker** [comment]
I think it's leaving enough horizontal space to display the string "\mathcal{E}" rather than "ℰ". I'll see what I can do with it, but one workaround for this particular circuit is to skip the Latex math and just use the unicode symbol:

`    E = d.add(elm.BatteryCell().up().label('ℰ'))
`

**Comment by cdelker** [comment]
dfc2850
