### ISSUE TITLE
Feature Request: Ability to embed an element in another element

### ISSUE THREAD

**Issue by TheCleric** [cdelker/schemdraw#12]
I am currently using schemdraw to diagram some dynamic workflows using mostly `schemdraw.flow`. One thing I'm finding I'm needing though is the concept of embedding elements within each other. By that I mean if there is an overall block for a set of elements, then have the sub-elements within that. So for example I'm rendering this now (where `Package` is a parent of `Package\Schools` and `Package\Schools` is a parent of the other boxes):

![image](https://github.com/cdelker/schemdraw/assets/547567/38025296-5d57-4188-b4cb-7a3859834598)

What would be preferable would be something like:

![image](https://github.com/cdelker/schemdraw/assets/547567/ff1e5098-9f24-4959-b0d8-8f491da953a2)

I think there are some ways to do this manually by rendering the children first, and then assign a width, height, and zorder to the parent, but this feels hacky in terms of the chaining that `schemdraw` seems to use.

A possible method from this would be adding a `.inner()` and `.outer()` to the element (like you can do `.up()`, `.down()`, etc.) to signal that the next element should be placed within that element via `.inner()` and to break out of this by adding `.outer()`. These could also be chained so `.up().inner()` would start drawing at the inside top, and `.outer().down()` would begin drawing outside the container going down.

**Comment by cdelker** [comment]
A nested context manager may be a good way to do this. Here's a mock-up I started:

```
with schemdraw.Drawing() as d:
    d += flow.Start().label('Start')
    d += flow.Arrow().down()
    with d.container() as c:
        c += flow.Box().label('Step 1').drop('E')
        c += flow.Arrow().right()
        c += flow.Box().label('Step 2')
        c.label('Subprocess', loc='N', halign='center', valign='top')
```
![download](https://github.com/cdelker/schemdraw/assets/44102190/d67b1525-8b25-45d6-bc37-c7831d0d99d7)

**Comment by cdelker** [comment]
Container element, as described above, was added in version 0.18.
