### ISSUE TITLE
tkinter integration

### ISSUE THREAD

**Issue by zorce** [cdelker/schemdraw#13]
Tries to get the matplotlib integration to work with the tkinter matplotlib backend. But cant seem to get the drawing to work with FigureCanvasTkAgg

AttributeError: Figure.show works only for figures managed by pyplot, normally created by pyplot.figure()

Any ideas on how to fix this? Bellow is a small snippet example.

```
from tkinter import *
from tkinter import ttk

import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg, NavigationToolbar2Tk

import schemdraw
import schemdraw.elements as elm

class Overview(Tk):

    def __init__(self):
        super().__init__()

        self.title('Overview')

        frame = ttk.Frame(self)
        frame.pack()
        ttk.Label(frame, text="hello").pack()

        drawing = schemdraw.Drawing()
        drawing.add(elm.Capacitor())
        drawing.add(elm.Resistor())
        drawing.add(elm.Wire('-').color('red'))

        fig = plt.Figure(tight_layout=True)
        canvas = FigureCanvasTkAgg(fig, self)
        ax = fig.subplots()
        ax.set_aspect('equal')

        canvas.draw()
        drawing.draw(canvas=ax)

        canvas.get_tk_widget().pack()

if __name__ == '__main__':

    app = Overview()
    app.mainloop()

```

**Comment by TheCleric** [comment]
I was able to get SOMETHING to work here, though I'm unsure if it's what you were hoping for. If you change your `drawing.draw(...)` call to `drawing.draw(canvas=ax, backend="matplotlib")` it does show a diagram instead of an error.

**Comment by zorce** [comment]
Yes that generates a matplotlib diagram, but in a separate window, but I try to integrate the diagram into my app to show the current state of a simple electrical circuit.

**Comment by zorce** [comment]
That will draw circuit diagram in a separate matplotlib window, but I'm looking for an integrated diagram in my tkinter frame.
Also tried with the latest version and newer python, but get the same error. But in with the warning now "DeprecationWarning: Use of `backend` is deprecated. Use `canvas`. drawing.draw(canvas=ax, backend='matplotlib')"

**Comment by TheCleric** [comment]
Ahh, I think I figured it out! Try `drawing.draw(canvas=ax, show=False)`

**Comment by zorce** [comment]
Ah nice!! Thanks!
