### ISSUE TITLE
Auto-size flowchart elements

### ISSUE THREAD

**Issue by cdelker** [cdelker/schemdraw#15]
Flowchart elements currently must be sized manually to fit their contents. It would be easier to have schemdraw calculate the text bounding box and grow the box to fit.

**Comment by armagidon-exception** [comment]
Is this feature in development?

**Comment by cdelker** [comment]
Yes, the latest commit has a first attempt. Still needs some testing and tweaking.

**Comment by cdelker** [comment]
Auto-sizing released in 0.18.
