### ISSUE TITLE
fix(ElementCompound): font fix when using Drawing.config font

### ISSUE THREAD

**Issue by lucaskatayama** [cdelker/schemdraw#16]
# Problem
Using `Drawing.config` to set config doesn't apply to `ElementCompound`.

e.g.

```python
import schemdraw
import schemdraw.elements as elm

class Test(elm.compound.ElementCompound):
    def __init__(self, *d, **kwargs):
        super().__init__(*d, **kwargs)
        self.add(elm.Resistor().label('10R'))


with schemdraw.Drawing() as d:
    d.config(font='Arial')
    d += Test()
```

<img width="144" alt="image" src="https://github.com/cdelker/schemdraw/assets/492687/6cc20852-ff75-47e3-a883-a80fc9a36e83">

# Expect

<img width="142" alt="image" src="https://github.com/cdelker/schemdraw/assets/492687/4ae86435-1e5f-43ee-83d2-b921b2b1491d">

**Comment by lucaskatayama** [comment]
Opened a PR #17

**Comment by kzhk75** [comment]
If we want to change font in latex mode , like `$R$`, how can we do?
In Schemdraw, `mathfont`  seems one choice, but I can not set as `schemdraw.config(lw=1, mathfont='cmb10')`.

**Comment by cdelker** [comment]
It's not documented, but you can pass mathfont to `schemdraw.Drawing(mathfont=...)`. It can be added to `config` to be consistent. If that doesn't work for you, please open a new issue.

**Comment by kzhk75** [comment]
Thanks. `schemdraw.Drawing(mathfont='cm')` works well,
but `schemdraw.config(...)` can NOT receive `mathfont='cm'`.
so, I opened https://github.com/cdelker/schemdraw/issues/33#issue-2235420039.
