### ISSUE TITLE
AnalogNFet has no drain element

### ISSUE THREAD

**Issue by davidparent** [cdelker/schemdraw#18]
We were trying to reproduce the 5-transistor OTA.  When we get an error: AttributeError: drain not defined in Element

Here is the link to our col-lab code: https://colab.research.google.com/drive/1cwWHiGRlmKUBavCjhQEOL7jpQqm7cqef?usp=sharing

Any help is greatly appreciated.

**Comment by cdelker** [comment]
I think you copied the example from the development documentation, which will not be supported under schemdraw 0.17 in pypi. Use the example from [the stable version](https://schemdraw.readthedocs.io/en/stable/gallery/analog.html#transistor-operational-transconductance-amplifer-ota).

The difference is a new experimental feature that would automatically add elements to the drawing, so the `d +=` becomes unnecessary. In 0.17,  `d +=` or `d.add` is required to add each element, and the anchor attributes defined only after one of those adds the element to the drawing.

**Comment by cdelker** [comment]
0.18 was released. Closing this issue.
