### ISSUE TITLE
Import external image like SVG, PNG, BMP

### ISSUE THREAD

**Issue by RadekValtera** [cdelker/schemdraw#22]
Hello

is there any way to insert an external image into the schematic please?
I would like to use various images of PLC or LCD or other compoment that are freely available on manufacturers' websites and insert them into the schematic.

Thank you for your answer

**Comment by cdelker** [comment]
There's no direct way to do this right now. But if drawing on a Matplotlib axis (the default if Matplotlib is installed), you could add images to the axis after drawing, something like:

```python
d = schemdraw.Drawing()
d += elm.Gap()  # Put resistor image here
d += elm.Capacitor().down()
d.draw()

imgax = d.fig.ax.inset_axes([0, -.375,  # Lower left corner, in drawing units
                             3, .75],   # width, height in drawing units
                            zorder=0,   # Put it below other elements
                            transform=d.fig.ax.transData)
img = plt.imread('resistor.png')
imgax.imshow(img)
imgax.axis('off')
d
```
![image](https://github.com/cdelker/schemdraw/assets/44102190/340bf78a-25dd-4872-b83c-300d4e31a999)

For a longer term solution, I'd propose something like a new `ElementImage` class, which takes an image file or bytes. It could be subclassed something like this, to specify the image, size, and add anchors or other drawing segments:

 ```python
class LCD(ElementImage):
    def __init__(self, **kwargs):
        super().__init__(image='lcd.png', width=6, height=1, **kwargs)
        self.anchors['gnd'] = (0, 0)
        self.anchors['D0'] = (.5, 0)
        # etc.
```

**Comment by cdelker** [comment]
A new `ElementImage` class was added in 37d7d05. See an [example here.](https://schemdraw.readthedocs.io/en/latest/elements/images.html)
