### ISSUE TITLE
Enable the reverse in the CurrentLabel

### ISSUE THREAD

**Issue by jangenoe** [cdelker/schemdraw#23]
Should we just replace this [false](https://github.com/cdelker/schemdraw/blob/859efd802dd63ed9721e46f06dbf99c1c9a74ea4/schemdraw/elements/lines.py#L780C30-L780C35)  by `reverse` to enable the reverse in the CurrentLabel

**Comment by cdelker** [comment]
Should be fixed in 9e85a82359abdb7f825668f087f7fb8a6c0a642b.

**Comment by jangenoe** [comment]
Thanks for the update. It works perfect in the current unreleased 0.19a0 version.
