### ISSUE TITLE
Handling long pin names in Ic elements

### ISSUE THREAD

**Issue by abradd** [cdelker/schemdraw#29]
With the following example code:

``` python
import schemdraw
import schemdraw.elements as elm
    
with schemdraw.Drawing(file="test.svg") as d:
    d.config(fontsize=12)
    axi_uart = elm.Ic(pins=list(reversed([
                     elm.IcPin(name='pin1', side='left'),
                     elm.IcPin(name='pin2', side='left'),
                     elm.IcPin(name='pin3', side='left'),
                     elm.IcPin(name='pin4', side='left'),
                     elm.IcPin(name='pin5', side='left'),
                     elm.IcPin(name='pin6', side='left'),
                     elm.IcPin(name='pin7', side='left'),
                     elm.IcPin(name='pin8_with_long_name', side='left'),
                     ])),
                pinspacing=0.5,
                leadlen=1,
                #size=[8,10],
                label='TEST_IC')

```

I get the following image:

![pinspacing_nosize](https://github.com/cdelker/schemdraw/assets/3516589/d53e0772-7494-4887-9f1c-6a477e335d52)

There are two concerns with this image:

- pin names clash with element label
- long pin names overrun the element width

If I uncomment the the `size` parameter to produce an element with the necessary width I get:

![nopinspcaing_size](https://github.com/cdelker/schemdraw/assets/3516589/3a83f8a0-4b12-4977-ae1b-cf7bb92d2e78)

where the `pinspacing` parameter is ignored and pins are evenly distributed along the left side.

- For pins that are evenly distributed, how does one connect them to a bus using a BusConnect element?
- Is it possible to define a size and have the pinspacing parameter honored? I imagine this would require the pins to be snapped to an edge (top or bottom in this example) or centered as they wouldn't completely fill the edge
- Is it possible to automatically scale the size of the element to accommodate all pin names without overrunning/overlapping other labels/elements?

Thanks

**Comment by cdelker** [comment]
In ae1abbb, Ic was fixed to respect pinspacing when size is also provided. It also adds a `pinspacing` attribute to the Ic element, so that you can use this to get them to line up, even when pinspacing is set automatically:

```
ic = Ic(...)
BusConnect(dy=ic.pinspacing)
```

It should be possible to have the size automatically determined based on labels too - just like the flowchart elements can do now. But that will be another commit.

**Comment by cdelker** [comment]
Autosize based on labels added: e66a7cb67bccd4b419794bfddae23b0a3097493a
