### ISSUE TITLE
The last element is not shown when d.draw() within the context

### ISSUE THREAD

**Issue by pozitron57** [cdelker/schemdraw#31]
`print(schemdraw.__version__)` 0.19a0

Not sure if this is intended behavior, but I noticed that the last element is not shown using `d.save()` or
`d.draw()` if used inside the context.

``` python
import schemdraw
import schemdraw.elements as elm

with schemdraw.Drawing() as d:
    R = elm.Resistor()
    elm.Line().down()
    elm.Capacitor().tox(R.start)
    elm.Lamp().to(R.start)
    d.draw()
```
 
<img width="216" alt="image" src="https://github.com/cdelker/schemdraw/assets/9392655/c548a744-8e29-4baf-b482-fed1bd01feec">

while the same code with last line shifted left gives
<img width="250" alt="image" src="https://github.com/cdelker/schemdraw/assets/9392655/604da541-f800-49c8-87ad-2dbd30e12cc7">

**Comment by cdelker** [comment]
The `draw()` should be unnecessary since exiting the context manager takes care of drawing already. But dd509fc692cca00490e50941d0543c3203635aeb fixes it so that calling `draw` within the context flushes the element list and works as expected.
