### ISSUE TITLE
fail to pass `mathfont=cm` to `config`

### ISSUE THREAD

**Issue by kzhk75** [cdelker/schemdraw#33]
I want to change `mathfont` in `schemdraw`.

Thanks to https://github.com/cdelker/schemdraw/issues/16#issuecomment-2046289085, 
I can change `mathfont` with `schemdraw.Drawing(mathfont='cm')`.
(other choices are 'dejavusans', 'dejavuserif', 'cm', 'stix', 'stixsans' in google colaboratory.)
this seems as a bit redundant because we should set it for every picture.

Can we pass `mathfont=cm` to `config` directly? 

The following link is my simple example with  `TypeError`:
https://colab.research.google.com/drive/1gCJIqDvQAq-ktWa9zjFN8ubzHjs8Yg_z?usp=sharing

**Comment by cdelker** [comment]
Added the `mathfont` parameter to `schemdraw.config()` and to `schemdraw.Drawing.config()`.

Fixed in 527f7956f1c80f1afded3ea2f01bc7f35d89523c and 1bd7c2236937b288ca0ba32280044d87c05beb62.
