### ISSUE TITLE
Unable to specify fonts but only when using ziamath

### ISSUE THREAD

**Issue by Stephenmccaul** [cdelker/schemdraw#37]
This is on MacOS using python 3.11 schemdraw 0.18 rendering to svg files.

For labels I would like to specify a particular font for both style sake and because of the need of a few esoteric unicode characters. This works fine if I do not have ziamath installed. Once I install ziamath my font name choices no longer work. I'm using system installed TTFs.

Of course I would like to have LaTeX rendering but this breaks many of our labels. Sadly the label text font requirements are more important to us than pretty math so our current workaround is to have ugly math :(

**Comment by cdelker** [comment]
Ziamath isn't currently able to locate a system-installed font by name, it only takes a full path to the ttf/otf file. This would be a good feature to have, so I opened https://github.com/cdelker/ziafont/issues/3.

**Comment by cdelker** [comment]
Enabled with ziamath 0.11.
