### ISSUE TITLE
Saving timing diagrams, truth tables and others

### ISSUE THREAD

**Issue by jangenoe** [cdelker/schemdraw#42]
Please note somewhere in the documentation that:

- [Timing diagrams](https://github.com/cdelker/schemdraw/blob/bc4a4c8b35cfc77b84b16cd58a18dd57ba89015d/schemdraw/logic/timing.py#L84)
- [Truth tables](https://github.com/cdelker/schemdraw/blob/bc4a4c8b35cfc77b84b16cd58a18dd57ba89015d/schemdraw/logic/table.py#L44)
- [Karnaugh Maps](https://github.com/cdelker/schemdraw/blob/bc4a4c8b35cfc77b84b16cd58a18dd57ba89015d/schemdraw/logic/kmap.py#L10)

are all `elements`. This is excellent, because this enables them to be added inside a schematic, explaining the functionality. But elements cannot be saved as such.

There is however a very easy and convenient way to save them, i.e. by adding them to a drawing using a single element. The example below saves a timing diagram from the tutorial in the file `test.png`
```
from schemdraw import logic
import schemdraw

with schemdraw.Drawing(file='test.png'):
       logic.TimingDiagram({'signal': [
        {'name': 'clk', 'wave': 'P......'},
        {'name': 'J', 'wave': '0101', 'async': [0, .8, 1.3, 3.7, 7]},
        {'name': 'K', 'wave': '010101', 'async': [0, 1.2, 2.3, 2.8, 3.2, 3.7, 7]},
        {'name': 'Q', 'wave': '010.101', 'color': 'red', 'lw': 1.5},
        {'name': r'$\overline{Q}$', 'wave': '101.010', 'color': 'blue', 'lw': 1.5}],
         'config': {'hscale': 1.5}}, risetime=.05)
```

**Comment by cdelker** [comment]
Added notes in d4d1ba4c8a41fc1ad525403d23c6418de79501ce.
