### ISSUE TITLE
Timing diagram - edge validation

### ISSUE THREAD

**Issue by dmitrisaberi** [cdelker/schemdraw#46]
Hey there!

I'm a huge fan of this lib and it's easily my favorite timing diagram tool out there (so thank you guys!). One small issue came up recently. When you make a new timing diagram, e.g. as follows:

```
    try:
        timing_diagram = logic.TimingDiagram(diagram_spec)
        drawing = schemdraw.Drawing()
        drawing += timing_diagram
        return drawing
    except Exception as e:
        return None
```

there are some strict requirements on, for example, the structure of `diagram_spec['edge']`. when setting `ls` in one of the edges, it needs to be one of the options supported by matplotlib. so when you call `.save()` on your drawing, you might run into something like this:

```
  File "/Users/dmitrisaberi/anaconda3/lib/python3.11/site-packages/matplotlib/lines.py", line 360, in __init__
    self.set_linestyle(linestyle)
  File "/Users/dmitrisaberi/anaconda3/lib/python3.11/site-packages/matplotlib/lines.py", line 1170, in set_linestyle
    _api.check_in_list([*self._lineStyles, *ls_mapper_r], ls=ls)
  File "/Users/dmitrisaberi/anaconda3/lib/python3.11/site-packages/matplotlib/_api/__init__.py", line 131, in check_in_list
    raise ValueError(msg)
ValueError: 'gray' is not a valid value for ls; supported values are '-', '--', '-.', ':', 'None', ' ', '', 'solid', 'dashed', 'dashdot', 'dotted'
```

I propose enforcing this requirement earlier, so you're not working with a timing diagram that only complains as soon as you try to save it -- for example, with a regex like this:

```
EDGE_REGEX_PATTERN = r"\[([\w\^\.]+):([\d\.]+)\](<->|\+|\-)\[([\w\^\.]+):([\d\.]+)\](?:\{(\w+),(solid|dashed|dashdot|dotted|None|-|--|\-.|:| )\}|\{(?!.*\}))*\s*(?:\$\w+\{\w+\}\$|[\w\s]+)?$"

```

**Comment by cdelker** [comment]
Agreed these errors would be good to raise before the drawing/saving happens. Especially when drawing to SVG which will just silently fail or ignore the invalid style/color option, unlike Matplotlib which raises an exception. Note these checks should really be done on all elements, not just TimingDiagrams.

**Comment by cdelker** [comment]
Added in 71e04295e9b1dc49b3a8f0fe39a2757097b041e5.
