### ISSUE TITLE
Header/footer in timing diagrams?

### ISSUE THREAD

**Issue by dmitrisaberi** [cdelker/schemdraw#47]
Right now, it doesn't seem like schemdraw renders headers or footers in timing diagrams. For example, with the following waveJSON:

```
{
        "signal": [
            {"name": "CLK_A", "wave": "P.......", "period": 2},
            {"name": "CLK_B", "wave": "P.......", "phase": 1},
            {
                "name": "Align Signal",
                "wave": "0.1..0.1",
                "data": ["Start Align", "End Align"],
            },
            {"name": "Block A Output", "wave": "x.3x=x=x=x", "data": []},
            {"name": "Block B Output", "wave": "x.3x=x=x=x", "data": []},
        ],
        "edge": ["[0^:3]+[0^:7] $t_{Align}$"],
        "head": {"text": "Phase Alignment Timing Diagram"},
        "foot": {"text": "Phase alignment process between FPGA Block A and Block B"},
    }
```

Wavedrom renders this OK, but using schemdraw, the text at the top and bottom is missing once the diagram is rendered. Would be awesome to support this!

**Comment by cdelker** [comment]
The `head` and `foot` parameters are implemented in aeb223d70c3647f5548983b642a7aedcdd11a01f, along with `tick`/`tock`/`every` for numbering waveform periods. Note using `tspan` in the `text` is not implemented at this time.
