### ISSUE TITLE
Label on CurrentLabel ignores global lblofst value

### ISSUE THREAD

**Issue by Ingegneus** [cdelker/schemdraw#51]
I am very new to this, but i think I found a possible bug. when changing the global `lblofst` value with `schemdraw.config(lblofst=1)` the labels above the arrows dont change their offset. all the other labels do.
![image](https://github.com/user-attachments/assets/9a610b60-e557-463c-ac90-ae55359c32ad)

**Comment by cdelker** [comment]
Fixed in 755a4435383f54333bee6f3c64e9059aaeecf8dd
