### ISSUE TITLE
arrow/head with setting for Arrow elements confusion

### ISSUE THREAD

**Issue by Ingegneus** [cdelker/schemdraw#52]
in the documentation it is stated that `Arrows()` takes the `headwidth` argument, but in fact it doesn't seem to be doing anything. intead using `arrowwidth` produces the right result. either this is an error in the code, or the documentation

**Comment by cdelker** [comment]
Fixed in 755a4435383f54333bee6f3c64e9059aaeecf8dd. Arrow inherits from Line, so now both use `arrowhead` and `arrowlength` for consistency.
