### ISSUE TITLE
Whitespace

### ISSUE THREAD

**Issue by pozitron57** [cdelker/schemdraw#6]
Typically in my svg plots there is 10-20pt of a whitespace margin. It is inconvenient when display these images in the html page. Is it possible to trim all the whitespace from the plots?

**Comment by cdelker** [comment]
In matplotlib backend, I had to add `ax.margins(0)` in addition to `bbox_inches='tight'` to completely remove the whitespace. Since some applications may prefer some margin, I added a config option to `schemdraw.config` to put it back, with no margin being the default. 6bbb987
