### ISSUE TITLE
No input/output labels when using logicparse

### ISSUE THREAD

**Issue by paulvicioso** [cdelker/schemdraw#7]
When using logicparse to generate a scheme the labels for the inputs/outputs are not showing in the final image. The code I have is as follows:

`from schemdraw.parsing import logicparse`
`circuit = logicparse('not ((w and x) or (y and z))', outlabel='$\overline{Q}$')`
`circuit.draw()`

This code generates the correct scheme but no labels whatsoever. At this point I'm not sure if this is an issue with my implementation.

The configuration of my machine is as follows:
- macOS Monterey 12.6.5
- Python 3.11.1
- schemdraw==0.16
- pyparsing==3.0.9

**Notes:**
- I tried this code on Google Colab with the same results.
- I also tried changing the format using `schemdraw.use('svg')` with the same results.

Thanks for your support.

**Comment by cdelker** [comment]
I believe I fixed this issue a couple weeks ago with 6871429.

**Comment by paulvicioso** [comment]
Yes you did, I have just used your code for v0.17 and now everything works great.

Thank you

**Comment by cdelker** [comment]
Thanks. 0.17 is now released on PyPi.
